name: Release Draft
on:
  push:
    branches:
      - main

jobs:
  releaseDraft:
    name: Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2.3.5
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Link yarn dependencies
        run: yarn

      - name: Set changelog
        run: export CHANGELOG="$(yarn standard-version --dry-run | sed -n '/^---$/,/^---$/p' | sed '1d;$d')"

      - name: Set version
        run: |
          yarn standard-version --skip.commit --skip.tag
          export RELEASE_VERSION=$(node -e "console.log(require('./package.json').version);")

      # Remove old release drafts by using the curl request for the available releases with draft flag
      - name: Remove Old Release Drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/{owner}/{repo}/releases \
            --jq '.[] | select(.draft == true) | .id' \
            | xargs -I '{}' gh api -X DELETE repos/{owner}/{repo}/releases/{}

      # Create new release draft - which is not publicly visible and requires manual acceptance
      - name: Create Release Draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v$RELEASE_VERSION \
            --draft \
            --title "v$RELEASE_VERSION" \
            --notes "$CHANGELOG"
