name: Test
on:
  workflow_dispatch:
    inputs:
      forceVersionType:
        description: "Force specific versioning type"
        default: "-"
        type: choice
        required: false
        options:
          - "-"
          - "major"
          - "minor"
          - "patch"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Set changelog, version and tag
        env:
          FORCE_VERSION_TYPE: ${{ github.event.inputs.forceVersionType }}
        run: |
          [[ "$FORCE_VERSION_TYPE" != "-" ]] && echo yarn standard-version --as-version $FORCE_VERSION_TYPE || echo yarn standard-version
